CXX=g++
CXXFLAGS=-std=c++11

all: proj_4

proj_4: proj_4.cpp
	$(CXX) $(CXXFLAGS) proj_4.cpp -o proj_4

# hashtable.o: hashtable.cpp
#     $(CXX) $(CXXFLAGS) -c hashtable.cpp

# tree.o: binary_tree.cpp
#     $(CXX) $(CXXFLAGS) -c tree.cpp

# proj_4: proj_4.o
#     $(CXX) $(CXXFLAGS) proj_4.o -o proj_4

clean:
	rm -f *.o proj_4
